CREATE TYPE ORGANIZATION_TYPE AS ENUM('COMPANY', 'PUBLIC', 'NGO');
CREATE TYPE ORGANIZATION_SIZE AS ENUM('SOLO', 'SMALL', 'MEDIUM', 'ENTERPRISE');
CREATE TYPE ORGANIZATION_STATUS AS ENUM('ACTIVE', 'INACTIVE', 'ARCHIVED');

CREATE TABLE IF NOT EXISTS organizations (
    id          BIGSERIAL PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    type        ORGANIZATION_TYPE NOT NULL,
    size        ORGANIZATION_SIZE NOT NULL,
    contact     VARCHAR(255) NOT NULL DEFAULT '',
    website     VARCHAR(255) NOT NULL DEFAULT '',
    status      ORGANIZATION_STATUS NOT NULL DEFAULT 'ACTIVE',

    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);