name: Build and deploy naturex-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
          

        # release 폴더 만들고 하위에 dist/, .env, .package.json,
        # tsconfig.json, tsconfig.build.json, naturex-backend.service를 이동시킵니다.
      - name: Move necessary files and folder
        run: |
          mkdir release
          cp -rf dist release
          cp -f package.json release
          cp -f tsconfig.json release
          cp -f tsconfig.build.json release
          cp -f naturex-backend.service release

        # release 내부의 폴더 및 파일들을 압축합니다.
      - name: Zip artifact for deployment
        run: |
          cd release
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    environment: production
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy over SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "release.zip"
          target: "~"

      - name: Cleanup and unzip on naturex-backend & move .service, .env
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf naturex-backend
            mkdir naturex-backend
            unzip release.zip -d naturex-backend
            rm release.zip
            mv -f naturex-backend/naturex-backend.service /etc/systemd/system
            mv -f .env.naturex-backend naturex-backend

      - name: Restart systemd service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd naturex-backend
            npm install --omit=dev
            sudo systemctl daemon-reload
            sudo systemctl restart naturex-backend
